### ISSUE TITLE
gmcl_midi_linux.dll is not loading on Linux clients

### ISSUE THREAD

**Issue by Synergyst** [FPtje/gmcl_midi#1]
- I have downloaded the pre-compiled Linux library for GMod, and I have installed it into my game under: 'GarrysMod/garrysmod/lua/bin/gmcl_midi_linux.dll'
- I have also downloaded the source code for the library and I have compiled it using premake(on Linux), which still fails to load once I am in-game..
- Although the Windows library works perfectly without any compiling from source!
- I have only tested this on a multiplayer server, where other clients have been able to get this working using Windows(including me, as I stated above), although it does NOT work on Linux(as stated in this issue report)..
- EDIT: I forgot to mention - I am using JACKd, and I am unable to see an ALSA or MIDI device show up under my QJackCtl GUI area..

I'm unsure if anyone else that has used this has gotten the library working on Linux in the previous releases.

**Comment by FPtje** [comment]
Linux is not supported at all. Sorry.
