### ISSUE TITLE
Crashing with new gmod update?

### ISSUE THREAD

**Issue by pablo67340** [FPtje/gmcl_midi#2]
Not sure what to exactly report. I have a very simple script hooked up to allow me to play the Piano with a MIDI file, after the most recent update I am noticing instant crashes. Know anything that would cause this inside gmcl_midi?

**Comment by FPtje** [comment]
![hl2_2016-10-26_22-19-31](https://cloud.githubusercontent.com/assets/1202014/19743631/485ea10a-9bca-11e6-9459-39b7192f58cf.png)
Still works for me. I don't know what could be causing crashes.
