### ISSUE TITLE
Add Windows 64 bit support

### ISSUE THREAD

**Issue by TinySimon** [FPtje/gmcl_midi#4]
With 64 bit GMod in beta, it would be great to have a compatible 64 bit MIDI module.

**Comment by FPtje** [comment]
This is the point where you find out after 4 years that the `compiling.md` file doesn't *really* describe how to compile this thing in detail. Oh well, I'll have to mess around a bit.

**Comment by FPtje** [comment]
This wasn't easy. After messing with three versions of visual studio, and struggling with the very little documentation I had written, I finally got it to work.

See https://github.com/FPtje/gmcl_midi/releases/tag/v0.2.0
