### ISSUE TITLE
Linux Mint port not opening :(

### ISSUE THREAD

**Issue by beingsuz** [FPtje/gmcl_midi#5]
![image](https://user-images.githubusercontent.com/42787030/59013826-06b32e00-8809-11e9-9d94-dcf62ca6382f.png)

the only Linux binary working is the v0.0.3 and `midi.IsOpened()` always return false :(

**Comment by FPtje** [comment]
Yes, like said in the releases tab they were removed from the latest release because they were untestedand I didn't expect them to work in the first place. Linux is not supported.

**Comment by beingsuz** [comment]
ok, if you ever change ur mind im ready to test them on my pc
