### ISSUE TITLE
Linux x64 (ALSA / JACK) compiles properly, but cannot load in-game

### ISSUE THREAD

**Issue by inco-cc** [FPtje/gmcl_midi#6]
this is on the x86-64 branch. I forked this repo and updated to the latest [gmod-module-base](https://github.com/Facepunch/gmod-module-base) headers (ones on here don't support Linux x64), and did a quick fix on `gmcl_midi.cpp` that errors on compiling due to the latest `Types.h` using `Number` instead of `NUMBER`

after doing all that, I generated the make files with `BuildProjects.sh` (shell script variant of `BuildProjects.bat` that I made), used the `linux-gmake` project, edited `gmcl_midi.make` and ran `make config=release_x64 clean gmcl_midi` to build the module

trying it out in-game (as `gmcl_midi_linux64.dll` in `lua/bin`) with the example script, it does actually load as expected, but of course doesn't find any midi input ports, despite having one listed with `amidi -l`, since RtMidi wasn't compiled to use ALSA or JACK. this was expected as it was mentioned in `Compiling.md`, I just wanted to see if it'd at least load in the first place

so after manually editing `gmcl_midi.make` to add the necessary compile options for RtMidi (`-D__LINUX_ALSA__ -lasound -lpthread` or `-D__UNIX_JACK__ -ljack`, I've tried both), recompiling and firing up the game again, the module won't even load at all, giving the vague `Couldn't load module library!` Lua error in the console

I'm not really familiar with making Lua modules, let alone C++ in general, so please pardon any ignorance I may be showing - is there a way to debug the module to find out why it wont even load? the extremely vague Lua error GMod spits out hardly helps

**Comment by FPtje** [comment]
To be honest, I wasn't much experienced either, and I'm still not. I remember messing with Linux while creating this module and not getting it to work. To get this to work even on x64 Windows would be a lot of work for me. I think it's best to ask on the GLua related Discords, as the people there have much more experience with modules. If you do get it to work, I'd be very grateful to receive a PR.

I remember the module not seeing Midi devices on Windows, though, vaguely. It was some hidden error like the midi dependency not being loaded properly, or the functions not being called properly or something. It's too long ago.

I'm sorry for not being able to help you much.

**Comment by inco-cc** [comment]
I did manage to get it working actually! it turns out I think I was putting the definition `-D__LINUX_ALSA__` and library declarations `-lasound -lpthread` (I personally don't use JACK, so I need ALSA) in the wrong places, which turns out matters a whole lot since now I've got midi events going through the `GM:MIDI` hook

the only (minor) issue I've noticed is the timings for when the MIDI event happened are very inaccurate... my suspicion is on the systime code in `gmcl_midi.cpp` (`CLOCKS_PER_RATE` perhaps?), since it seems to be going like twice as slow for some reason, since using the example script shows events that happen immediately happening in the past more and more as time goes on. again, this is pretty a minor issue since I've never thought of a use case for using the time argument in `GM:MIDI` outside of debugging information - but this is for another issue tracker, of course

anyway, I appreciate the response - I can make a PR later and also provide the Linux x64 release, maybe even ask around for someone to help out with building an OSX release

**Comment by FPtje** [comment]
That's awesome!
