### ISSUE TITLE
Credits on Release page

### ISSUE THREAD

**Issue by AkikoKumagara** [FPtje/gmcl_midi#9]
Hey, friend! Both @inco-cc and I (formerly Sophie-bear, now @AkikoKumagara) are credited for the latest release, but we've also both changed our handles (and someone has since claimed mine). If this could be corrected, that'd be much appreciated. Sorry it's not *actually* an issue with the plugin, but I don't know where else to ask about this.

**Comment by FPtje** [comment]
Thanks for the report! I see that indeed @inco-cc is the author of the PR. Is there was way I can verify that you are indeed Sophie-bear? Thanks!

**Comment by AkikoKumagara** [comment]
> Thanks for the report! I see that indeed @inco-cc is the author of the PR. Is there was way I can verify that you are indeed Sophie-bear? Thanks!

My comment is from this account.
https://github.com/FPtje/gmcl_midi/pull/7#issuecomment-658287602

**Comment by FPtje** [comment]
Ah, of course. Fixed!
